### ISSUE TITLE
add monthly coworking to every newsletter

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/monthly#82]
coworking has 2 info sources:

- [general blog post](https://ropensci.org/blog/2021/08/17/coworking-sessions/)
- [one event per session](https://ropensci.org/events/)

note they alternate between timezones

Sample text in [this tweet](https://twitter.com/rOpenSci/status/1450507033594109957). Can use same info every month and ping Steffi to ask if there are any special guests to add (like Mark for Nov 2)

**Comment by maelle** [comment]
Thank you! Could you please make a PR editing https://github.com/ropensci/roweb3/blob/master/archetypes/newsletter/index.md so that the info lives in the newsletter template? With HTML comments for e.g. "Can use same info every month and ping Steffi to ask if there are any special guests to add (like Mark for Nov 2)". If not I'll tackle when I'm back.

**Comment by stefaniebutland** [comment]
done in https://github.com/ropensci/roweb3/pull/283

Please close this issue if satisfactory

**Comment by maelle** [comment]
Thanks a lot, perfect!
